spring.application.name=foodAndFlower

#cookie
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true

spring.datasource.url=jdbc:postgresql://dpg-d82oncd7vvec7389fl90-a.singapore-postgres.render.com:5432/db_bakery_b0vt?sslmode=require
spring.datasource.username=hung452005
spring.datasource.password=uuV815ikkvCOP7aYJtg5vfepT5zUfmdU
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.ai.openai.api-key=${GEMINI_KEY}
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai/
spring.ai.openai.embedding.base-url=https://generativelanguage.googleapis.com/v1beta/openai/

app.ai.primary-model=gemini-2.5-flash
app.ai.fallback-model=gemini-3.1-flash-lite

spring.ai.openai.embedding.options.model=gemini-embedding-001
spring.ai.openai.embedding.options.dimensions=768
spring.ai.openai.chat.options.model=gemini-3.1-flash-lite
spring.ai.retry.max-attempts=5
spring.ai.retry.backoff.initial-interval=2000
spring.ai.retry.backoff.multiplier=2
spring.ai.retry.backoff.max-interval=15000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${USERNAME_EMAIL}
spring.mail.password = ${PASSWORD_EMAIL}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true